# Generated by Django 4.1.7 on 2023-03-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('discount', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('kg', models.PositiveIntegerField()),
            ],
        ),
    ]
